account/urls.py
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', views.RegisterFormView.as_view(), name='registration'),
]

cinema/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'cinema'
urlpatterns = [
    path('', views.LoginPage.as_view(), name='Login'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='movie_detail'),
    path('search/', views.MovieSearch.as_view(), name='search'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cinema_api/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name= 'cinema_api'
urlpatterns = [
    path('test_api/', views.TestView.as_view(), name='test_view'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinema.urls')),
    path('api/', include("cinema_api.urls")),
    path('account/', include('account.urls')),
]

cinema/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

class Movie(models.Model):
    """
        Class to store movies
    """
    # Fields
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.DecimalField(max_digits=2,
                                 decimal_places=1,
                                 validators=[MinValueValidator(0),
                                             MaxValueValidator(10)])
    runtime = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images/')
    background = models.ImageField(upload_to='backgrounds/')
    video = models.URLField(max_length=180)

    # How object will be displayed in admin page
    def __str__(self):
        return "{} {}".format(self.title, self.year)

    def get_absolute_url(self):
        return reverse('cinema:movie_detail', args=[self.pk, ])

cinema/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic.edit import FormView
from django.contrib.auth import login, logout
from cinema.models import Movie
from account.models import Profile
from django.http import JsonResponse


class MovieDetail(DetailView):
    template_name = 'cinema/movie_detail.html'
    model = Movie

    def get_context_data(self, *args, **kwargs):
        # Call the base implementation first to get a context
        context = super(MovieDetail, self).get_context_data(**kwargs)
        #get profile user data from account.models
        context['profile'] = Profile.objects.get(user=self.request.user.pk)
        return context

class MovieSearch(View):
    def post(self, request, *args, **kwargs):
        search_text = request.POST['search_text']
        json_result = []
        if search_text is not None and search_text != u"":
            results = Movie.objects.filter(title__contains=search_text)
        else:
            results = []

        for movie in results:
            json_result.append({
                "title": movie.title,
                "url": movie.get_absolute_url(),
            })
        return JsonResponse({"result": json_result})

class LoginPage(FormView):
    form_class = AuthenticationForm
    # If successful, redirect to home.
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        # if user is authenticated than we need to display a main page with movies
        if request.user.is_authenticated:
            self.template_name = "cinema/movies_list.html"
        # if not, display login page instead
        else:
            self.template_name = "cinema/login-form.html"
        return super(LoginPage, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginPage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            #get profile user data from account.models
            context['profile'] = Profile.objects.get(user=self.request.user.pk)
            # get all Movies from database without filtration
            context['object_list'] = Movie.objects.all()
        else:
            # Call the base implementation first to get a context
            context['form'].fields['username'].label = ""
            context['form'].fields['username'].widget.attrs["placeholder"] = "username"

            context['form'].fields['password'].label = ""
            context['form'].fields['password'].widget.attrs["placeholder"] = "password"
            # get all Movies from database without filtration
            context['object_list'] = Movie.objects.all()
        return context

    def form_valid(self, form):
        # raise an error if user already authenticated
        if not self.request.user.is_authenticated:
            # We receive object of the user on the basis of the data entered into the form.
            self.user = form.get_user()
            # We perform user authentication.
            login(self.request, self.user)
        else:
            raise Http404
        return super(LoginPage, self).form_valid(form)

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")

cinema/templates/cinema/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang='en'>
<head>
  <meta http-equiv="content-type" content="text/html" charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="theme-color" content="#121212">
  <meta name="msapplication-navbutton-color" content="#121212">
  <meta name="apple-mobile-web-app-status-bar-style" content="#121212">
  <link href="{% static 'cinema/css/main.css' %}" rel="stylesheet" type="text/css" media="screen"/>
  <link href="{% static 'cinema/img/favicon.svg' %}" rel="icon" type="image/x-icon" />
  <link href="https://fonts.googleapis.com/css?family=Lobster|Oxygen" rel="stylesheet" >
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap-grid.min.css" integrity="sha256-vl+0p/Z28RcVvC+cofUiIeYusGdOc4CXk/taqgQ2/XU=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover-min.css" integrity="sha256-c+C87jupO1otD1I5uyxV68WmSLCqtIoNlcHLXtzLCT0=" crossorigin="anonymous" />
  <title>{% block title %}Pasternak{% endblock %}</title>
</head>
<body>
  <div class="container-fluid" style="padding: 0px;">
    <header>
      <div class="width-navbar">
        <div class="row full" style="margin: 0px;">
          <div class="col centered" style="padding: 0px;">
            <div class="navbar-brand"><a href="/">Pasternak</a></div>
            <div class="search">
              {% csrf_token %}
              <div id="search-button">
                <a href="#"><img src="{% static 'cinema/img/search.svg' %}" alt=""></a>
              </div>
              <div id="search-show">
                <input type="text" placeholder="Search" aria-lable="Search" id="search" name='cinema:search' value="" style="background: #ffffff url({% static 'cinema/img/search.svg' %}) no-repeat scroll 16px 16px; padding-left:50px;">
                <a href="#" id="search-hide"><img src="{% static 'cinema/img/close.svg' %}" alt=""></a>
              </div>
            </div>
            <div class="navbar-account" id="account">
              <a href="#"><img src="{{ profile.image.url }}" alt=""></a>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div class="row full" style="margin: 0px;">
      <div class="col centered" id="click-hide">
        {% block main %}{% endblock main %}
        {% block sidebar %}{% endblock sidebar %}
      </div>
    </div>
    <!-- Search Result-->
    <div id="search_popup">
      <span id="search-results"></span>
    </div>
    <!-- Dropdown profile -->
    <div id="dropdown" class="centered">
      <div id="dropdown-container">
        <div class="dropdown-profile">
          <img src="{{ profile.image.url }}" alt="">
          <h4>Welcome, {{ profile.first_name }}</h4>
          <h5>{{ profile.user }}</h5>
        </div>
        <div class="dropdown-settings">
          <a href="{% url 'account:profile' %}"><p>Settings</p></a>
        </div>
        <div class="dropdown-logout">
          <a href="{% url 'cinema:logout' %}"><button type="button" name="button">Logout</button></a>
        </div>
      </div>
    </div>
  </div>

  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="{% static '/cinema/js/main.js' %}"></script>
  <script type="text/javascript">
  // Search results
  $(function() {
      $('#search').keyup(function() {
      if ($(this).val().length > 0) {
        $.ajax({
          type: "POST",
          url: '{% url "cinema:search" %}',
          data: {
              'search_text' : $(this).val(),
              'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val(),
          },
          success: searchSuccess,
        });
      } else {
        $( '#search-results' ).html('');
      }
    });
  });
  </script>
</body>
</html>

cinema/templates/cinema/login-form.html
{% extends 'cinema/login.html' %}
{% load staticfiles %}

{% block login %}
  <div class="login-form">
    <div class="user-icon">
      <img src="{% static 'cinema/img/user-icon.svg' %}" alt="">
    </div>
    <div class="past center-position">
      <h1 style='padding-bottom: 20px;'>Sing in</h1>
    </div>
    <form action="." method="post">
      <div class="center-pos">
        {% for forms in form.visible_fields%}
          <div class="login-input">
            {% csrf_token %}
            {{ forms }}
          </div>
        {% endfor %}
      </div>
      <div class="su-fp">
        <a href="#" id="fp">Forgot password?</a>
        <a href="account/" id="su">Sign Up</a>
      </div>
      <button type="submit"><img src="{% static 'cinema/img/3d.png' %}" alt="3d"></button>
    </form>
  </div>
{% endblock %}

<!-- Login Page Demo messege -->
{% block swal %}
  <script type="text/javascript">
    swal ( "Demo version" ,  "Login: demo \n Password: demodemo","info" )
  </script>
{% endblock %}

{% block login-mob %}
  <div class="login-form">
    <form action="." method="post">
      <div class="center-pos">
        <div class="login-input">
          <form action="." method="post">
          <h1>Sing in</h1>
          {% csrf_token %}
          {{ form.as_p }}
        </div>
      </div>
      <div class="su-fp">
        <a href="#">Forgot password?</a>
        <a href="account/">Sing Up</a>
      </div>
      <button onclick="validation();" type="submit"><img src="{% static 'cinema/img/3d.png' %}" alt="3d"></button>
    </form>
  </div>
{% endblock %}

cinema/templates/cinema/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <title>Welcome</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="theme-color" content="#0E3E4F">
    <meta name="msapplication-navbutton-color" content="#0E3E4F">
    <meta name="apple-mobile-web-app-status-bar-style" content="#0E3E4F">
    <link href="https://fonts.googleapis.com/css?family=Lato|Lobster|Staatliches" rel="stylesheet">
    <link href="{% static 'cinema/css/login.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap-grid.min.css" integrity="sha256-vl+0p/Z28RcVvC+cofUiIeYusGdOc4CXk/taqgQ2/XU=" crossorigin="anonymous" />
  </head>
  <body>
    <!-- Desktop -->
    <div class="container-fluid" id="desktop">
      <div class="row full">
        <div class="col center-position">
          <div class="text-wrapper">
            <h1 class="main-text" style="font-family: 'Lobster', cursive;">Pasternak</h1>
            <h2 class="main-text" style="font-size: 3vw; float: left;">cinema</h2>
          </div>
        </div>
        <div class="col center-position">
          {% block login %}{% endblock %}
        </div>
      </div>
    </div>
    <!-- Mobile -->
    <div class="container-fluid" id="mobile">
      <div class="row">
        <div class="col-xs center-position">
          <div class="header-line">
            <h1 class="main-text">Pasternak</h1>
          </div>
        </div>
        <div class="col">
          <style media="screen">
            .col{padding-left: 0px;}
          </style>
          {% block login-mob %}{% endblock %}
        </div>
      </div>
    </div>
    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- Swal aler -->
    <script type="text/javascript">
      $(function(){
        $('#fp').click(function(){
          swal ( "Oops" ,  "This feature does not work." ,  "error" );
        });
      });
   </script>
   {% block swal %}{% endblock swal %}
  </body>
</html>

cinema/templates/cinema/movie_detail.html
{% extends 'cinema/base.html' %}
{% block title %}{{ object.title }}{% endblock %}

{% block main %}
<div class="media-background" style="background-image: url('{{ object.background.url }}')"></div>
    <div class="main-content center-pos-horizontal">
      <div class="main-info">
        <div class="media-img">
          <img src=" {{ object.image.url }}" class="main-detail-img">
        </div>
        <div class="media-info">
          <h1 class="main-text">{{ object.title }} ({{ object.year }})</h1>
          <h2 class="main-plot" style='margin:0px;'>IMDb (<span style='color: #CFBB52;'>{{ object.rating }}</span>)</h2>
          <h2 class="main-plot">{{ object.plot }}</h2>
        </div>
      </div>
      <div class="video center-pos-horizontal center-pos-vertical">
        <iframe width="860" height="550" src="{{ object.video }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
    <footer>
      <h5>© 2019 Pasternak</h5>
    </footer>
{% endblock %}

cinema/templates/cinema/movies_list.html
{% extends 'cinema/base.html' %}
{% load staticfiles %}

{% block main %}
  {% for object in object_list %}
    <div class="main-content hvr-grow">
      <div class="main-imgs">
        <a href="{{ object.get_absolute_url }}" class="main-list-img"><img src="{{ object.image.url }}" alt="img"></a>
        <span class="rating">
          <h4>IMDB:</h4> {{ object.rating }} / {{ object.year }}
        </span>
        <a class="movie-text" href="{{ object.get_absolute_url }}">{{ object.title }}</a>
      </div>
    </div>
  {% endfor %}
{% endblock %}

{% block sidebar%}
  {% for object in object_list %}
  {% endfor %}
{% endblock %}

{% block domready %}
  <!-- API -->
  <script type="text/javascript">
    // API
    $.ajax({
      type: "GET",
      url: '{% url "cinema_api:test_view" %}',
      data: {
          'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val(),
      },
      success: function(data) {
        console.log(data);
        //$('.main-imgs').html("<a href=\"" + data["results"][0]["get_absolute_url"] + "\">" + '<img src="' +  data["results"][0]["image"] + '" ' + 'class="main-imgs">' + "</a> \n")
      },
    });
  </script>
{% endblock domready %}